# Package Overview
package_name: spd_trading

# Data Files
rnd_input_data_file: rnd_input_data.csv
hd_input_data_file: hd_input_data.csv

# # this variable is to calculate the temporal variable
# # but is dropped prior to model training.
# drop_features: YrSold

pipeline_name: spd_calculator
pipeline_save_file: spd_calculator_output_v

# Variables
# The variable we are attempting to predict (Risk Neutral Density q_M)
target: q_M

# # Will cause syntax errors since they begin with numbers
# variables_to_rename:
#   1stFlrSF: FirstFlrSF
#   2ndFlrSF: SecondFlrSF
#   3SsnPorch: ThreeSsnPortch

rnd_features:
  - M
  - iv
  - S
  - P
  - K
  - tau
  - option
    # this one is only to calculate temporal variable:
  - q_K

hd_features:
  - price
  - date_str

numerical_vars:
  - M
  - iv
  - S
  - P
  - K
  - tau
  - price

categorical_vars:
  - option
  - date_str

# temporal_vars: YearRemodAdd

# Validation
# # numerical variables with NA in train set
# numerical_vars_with_na:
#   - LotFrontage

numerical_na_not_allowed:
  - M
  - iv
  - S
  - P
  - K
  - tau
  - price

# # set train/test split
# test_size: 0.1

# to set the random seed
random_state: 1

# the number of slices for CV bandwidth selection for local polynomial 
# estimation
n_slices: 15

# # The number of boosting stages to perform
# n_estimators: 50

# loss function to be optimized
loss: ls
allowed_loss_functions:
  - ls
  - MSE
