# Package Overview
package_name: spd_trading

# Data Files
rnd_input_data_file: rnd_input_data.csv
hd_input_data_file: hd_input_data.csv

# Variables
# The variable we are attempting to predict (Risk Neutral Density q_M)
target: q_M

rnd_input_features:
  - M
  - iv
  - S
  - P
  - K
  - tau
  - option

hd_input_features:
  - price
  - date_str

numerical_vars:
  - M
  - iv
  - S
  - P
  - K
  - tau
  - price

categorical_vars:
  - option
  - date_str

numerical_na_not_allowed:
  - M
  - iv
  - S
  - P
  - K
  - tau
  - price

# to set the random seed
random_state: 1

# loss function to be optimized
loss: ls
allowed_loss_functions:
  - ls
  - MSE
